### ISSUE TITLE
add subcommand: update all clones

### ISSUE THREAD

**Issue by tamaskenez** [adasworks/cmakex#16]
should perform an ff-only git pull and report if it's not possible

**Comment by gorogm** [comment]
and check if deps.cmake specifies a different branch from the currently checked out?

**Comment by tamaskenez** [comment]
implemented in d9a5c1aeb3710d0b89dc504d33ead7a669e9fc10
there are 4 modes (see help), the `if-very-clean` and `all-very-clean` skip or stop if different branch is checked out
