### ISSUE TITLE
allow setting other locations for deps_install and deps

### ISSUE THREAD

**Issue by tamaskenez** [adasworks/cmakex#30]
--deps-install=..., default: CMAKE_BINARY_DIR/_deps-install
--deps-build=..., default: CMAKE_BINARY_DIR/_deps
--deps-source=..., default: CMAKE_BINARY_DIR/_deps

**Comment by csabakeszegh** [comment]
It would be great if build, and source would go to separate directories. I would recommend to use the following defaults:

--deps-install=..., default: CMAKE_BINARY_DIR/_deps-install
--deps-build=..., default: CMAKE_BINARY_DIR/_deps-build
--deps-source=..., default: CMAKE_BINARY_DIR/_deps-src

**Comment by tamaskenez** [comment]
fixed in 8739e9531b13a445c8128aa559bb0a4440f287c6
